let propiedades = [
    {
        tipo: "departamento",
        ambientes: 3,
        dormitorios: 2,
        baños: 1,
        tipoDeOperacion: "venta",
        cochera: "si",
        precio: 56000,
    },
    {
        tipo: "casa",
        ambientes: 4,
        dormitorios: 3,
        baños: 2,
        tipoDeOperacion: "venta",
        cochera: "si",
        precio: 85000,
    },
    {
        tipo: "lote",
        ambientes: 0,
        dormitorios: 0,
        baños: 0,
        tipoDeOperacion: "venta",
        cochera: "no",
        precio: 25000,
    },
    {
        tipo: "casa",
        ambientes: 3,
        dormitorios: 2,
        baños: 1,
        tipoDeOperacion: "alquiler",
        cochera: "no",
        precio: 5000,
    },
    {
        tipo: "departamento",
        ambientes: 2,
        dormitorios: 1,
        baños: 1,
        tipoDeOperacion: "venta",
        cochera: "si",
        precio: 45000,
    },
    {
        tipo: "casa",
        ambientes: 4,
        dormitorios: 2,
        baños: 2,
        tipoDeOperacion: "venta",
        cochera: "no",
        precio: 67000,
    },
    {
        tipo: "lote",
        ambientes: 0,
        dormitorios: 0,
        baños: 0,
        tipoDeOperacion: "venta",
        cochera: "no",
        precio: 15000,
    },
    {
        tipo: "casa",
        ambientes: 2,
        dormitorios: 1,
        baños: 1,
        tipoDeOperacion: "venta",
        cochera: "si",
        precio: 40000,
    },
    {
        tipo: "departamento",
        ambientes: 1,
        dormitorios: 1,
        baños: 1,
        tipoDeOperacion: "venta",
        cochera: "no",
        precio: 32000,
    },
    {
        tipo: "departamento",
        ambientes: 4,
        dormitorios: 3,
        baños: 2,
        tipoDeOperacion: "venta",
        cochera: "si",
        precio: 90000,
    },
    {
        tipo: "casa",
        ambientes: 6,
        dormitorios: 4,
        baños: 3,
        tipoDeOperacion: "venta",
        cochera: "si",
        precio: 120000,
    },
    {
        tipo: "departamento",
        ambientes: 2,
        dormitorios: 1,
        baños: 1,
        tipoDeOperacion: "alquiler",
        cochera: "si",
        precio: 7000,
    },
    {
        tipo: "lote",
        ambientes: 0,
        dormitorios: 0,
        baños: 0,
        tipoDeOperacion: "alquiler",
        cochera: "no",
        precio: 6000,
    },
    {
        tipo: "oficina",
        ambientes: 3,
        dormitorios: 0,
        baños: 2,
        tipoDeOperacion: "venta",
        cochera: "no",
        precio: 60000,
    },
    {
        tipo: "departamento",
        ambientes: 3,
        dormitorios: 2,
        baños: 1,
        tipoDeOperacion: "venta",
        cochera: "si",
        precio: 50000,
    },
    {
        tipo: "oficina",
        ambientes: 6,
        dormitorios: 0,
        baños: 3,
        tipoDeOperacion: "alquiler",
        cochera: "si",
        precio: 12000,
    },
    {
        tipo: "departamento",
        ambientes: 1,
        dormitorios: 1,
        baños: 1,
        tipoDeOperacion: "alquiler",
        cochera: "si",
        precio: 5000,
    },
    {
        tipo: "casa",
        ambientes: 4,
        dormitorios: 3,
        baños: 2,
        tipoDeOperacion: "venta",
        cochera: "si",
        precio: 75000,
    },
    {
        tipo: "oficina",
        ambientes: 3,
        dormitorios: 0,
        baños: 1,
        tipoDeOperacion: "alquiler",
        cochera: "si",
        precio: 8000,
    },
    {
        tipo: "galpon",
        ambientes: 1,
        dormitorios: 0,
        baños: 1,
        tipoDeOperacion: "alquiler",
        cochera: "si",
        precio: 15000,
    },
    {
        tipo: "campo",
        ambientes: 3,
        dormitorios: 2,
        baños: 2,
        tipoDeOperacion: "venta",
        cochera: "si",
        precio: 250000,
    },
    {
        tipo: "casa",
        ambientes: 4,
        dormitorios: 3,
        baños: 3,
        tipoDeOperacion: "venta",
        cochera: "si",
        precio: 90000,
    },
    {
        tipo: "campo",
        ambientes: 0,
        dormitorios: 0,
        baños: 0,
        tipoDeOperacion: "alquiler",
        cochera: "si",
        precio: 20000,
    },
    {
        tipo: "galpon",
        ambientes: 0,
        dormitorios: 0,
        baños: 1,
        tipoDeOperacion: "venta",
        cochera: "si",
        precio: 9000,
    },
    {
        tipo: "casa",
        ambientes: 2,
        dormitorios: 1,
        baños: 1,
        tipoDeOperacion: "alquiler",
        cochera: "si",
        precio: 5000,
    }
]

console.log(propiedades);